apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot'

        metrics_path: /actuator/prometheus

        static_configs:
          - targets:
              - proyecto-devops-app.proyecto-devops.svc.cluster.local:80